### ISSUE TITLE
training data format ?

### ISSUE THREAD

**Issue by ziodos** [lucky-verma/Invoice-Data-Extraction#1]
thank you for providing the code , I am still confused about the procedure to prepare data for training , can you please provide more explanations about this point ? thanks in advance

**Comment by lucky-verma** [comment]
Hey there! 

You can refer to this [video](https://youtu.be/FgtLRBNh36I) for YOLO data format preparation. 
Also, can use [LabelImg](https://github.com/tzutalin/labelImg) to prepare the dataset in YOLO format.

Feel free to ask anything. 😄

**Comment by ziodos** [comment]
thank you so much for your answer , one other thing .. can you mention the link of the paper that you implemented ? and can you provide the dataset that you used to train the model :D ?

**Comment by lucky-verma** [comment]
The base algo is borrowed from [here](https://github.com/ultralytics/yolov5) and [here](https://zenodo.org/record/4418161).
Sorry, the dataset is very limited & confidential. If you want to try the model you can download it from [here](http://vast-ml-models.s3-ap-southeast-2.amazonaws.com/Invoice+All++Class+(Object+Detection)+best.pt) by passing in the yolov5 package.

If facing problems do ping here!
